### ISSUE TITLE
It's not working 

### ISSUE THREAD

**Issue by fernandogprieto** [fernandogprieto/github-stats#1]
I see my profile and it's not working anymore. I checked the token and access is all good. Could you please check?

**Comment by Quando0987** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
